trigger:
- none

pool:
  vmImage: "windows-latest"
stages:
  - stage: Prod
    displayName: Prod
    dependsOn: []
    jobs:
      - template: /Devops/devops/jobs/db_jobs.yaml@self
        parameters:
          # Common Parameters to all Resources
          repo: self
          subscription: T
          location: East US
          resourceGroup: 
          serverName: 
          sqldbName: 
          storageKeyType: StorageAccessKey
          storageKey: 
        
          storageUri: https://
          adminUser: Cl
          adminPassword: 
          keyVaultName:

 
