parameters:
  - name: repo
    type: string
    default: self

  - name: location
    type: string
    default: ''

  - name: subscription
    type: string
    default: ''

  - name: resourceGroup
    type: string
    default: ''

  - name: serverName
    type: string
    default: ''

  - name: sqldbName
    type: string
    default: ''

  - name: storageKeyType
    type: string
    default: ''

  - name: storageKey
    type: string
    default: ''

  - name: storageUri
    type: string
    default: ''

  - name: adminUser
    type: string
    default: ''

  - name: adminPassword
    type: string
    default: ''
    
  - name: keyVaultName
    type: string
    default: ''

jobs:
  - job: PrivateDnsZone
    displayName: DQLDB Backup
    steps:
      - checkout: '${{ parameters.repo }}'
      - template: '/SpendkeyDevops/devops/steps/db_steps.yaml@${{ parameters.repo }}'
        parameters:
          repo: '${{ parameters.repo }}'
          subscription: '${{ parameters.subscription }}'
          location: '${{ parameters.location }}'
          resourceGroup: '${{ parameters.resourceGroup }}'
          serverName: '${{ parameters.serverName }}'
          sqldbName: '${{ parameters.sqldbName }}'
          storageKeyType: '${{ parameters.storageKeyType }}'
          storageKey: '${{ parameters.storageKey }}'
          storageUri: '${{ parameters.storageUri }}'
          adminUser: '${{ parameters.adminUser }}'
          adminPassword: '${{ parameters.adminPassword }}'
          keyVaultName: '${{ parameters.keyVaultName }}'

